### ISSUE TITLE
All mojos' parameters are not editable

### ISSUE THREAD

**Issue by cy6erGn0m** [Devexperts/bintray-maven-plugin#2]
All mojos parameters' annotations has parameter `editable = false` so that means that you can't specify values in the plugin's configuration. See https://maven.apache.org/developers/mojo-api-specification.html

This causes IntelliJ IDEA to mark configured parameters red in the pom with error message "Element ... is not allowed here".

**Comment by ndkoval** [comment]
Fixed in version 1.2
